import { ArrowRight, BarChart3, ChevronDown, MousePointer2, Plus, Quote, Target } from 'lucide-react';
import { bookingUrl, faqs, partnerLogos, testimonials } from '../data/siteData';
import SectionHeading from '../components/SectionHeading';
interface Props { navigate:(path:string)=>void; }
export default function Home({navigate}:Props){return <div className="pt-[76px]">
<section className="relative flex min-h-[670px] items-center overflow-hidden"><div className="glow left-1/2 top-0 -translate-x-1/2"/><div className="container relative text-center"><div className="reveal mx-auto mb-8 inline-flex items-center gap-2 rounded-full border border-white/[.1] bg-white/[.03] px-4 py-2 text-xs text-[#cdd2dc]"><span className="h-2 w-2 rounded-full bg-[#1e90ff] shadow-[0_0_14px_#1e90ff]"/>100+ Businesses Served</div><h1 className="display reveal mx-auto max-w-5xl text-5xl font-bold sm:text-6xl md:text-8xl">Go To Market Systems <span className="text-[#6bb7ff]">For Businesses Ready to Scale</span></h1><p className="reveal mx-auto mt-7 max-w-2xl text-lg leading-8 muted">We create demand, capture intent and convert it into booked revenue, all within one connected system.</p><div className="reveal mt-9"><a href={bookingUrl} className="button-primary">Talk with our team <ArrowRight size={17}/></a></div></div></section>
<section className="border-y border-white/[.07] py-10"><p className="mb-7 text-center text-xs uppercase tracking-[.2em] text-[#9aa0ab]">Companies that trust us to drive their revenue</p><div className="relative overflow-hidden before:absolute before:left-0 before:top-0 before:z-10 before:h-full before:w-24 before:bg-gradient-to-r before:from-[#0a0b0f] before:to-transparent after:absolute after:right-0 after:top-0 after:z-10 after:h-full after:w-24 after:bg-gradient-to-l after:from-[#0a0b0f] after:to-transparent"><div className="flex w-max animate-[marquee_24s_linear_infinite] items-center gap-20">{partnerLogos.map((logo,i)=><img key={`${logo.alt}-${i}`} src={logo.src} alt={logo.alt} loading="lazy" className="h-12 w-32 object-contain grayscale brightness-[1.8] opacity-70"/>)}<style>{'@keyframes marquee{to{transform:translateX(-50%)}}'}</style></div></div></section>
<section className="section-space"><div className="container"><SectionHeading eyebrow="What We Build" title="One System. Deployed to acquire sales opportunities and convert them into revenue." body="We create demand, capture intent and convert it into booked revenue, all within one connected system."/><div className="mt-12 grid gap-4 md:grid-cols-3">{[[Target,'01','Create Demand','Reach the right people through a considered mix of channels.'],[MousePointer2,'02','Capture & Convert','Turn attention into intent with clear, useful conversion paths.'],[BarChart3,'03','Close: Booked Revenue','Give your team qualified opportunities with context attached.']].map(([Icon,num,title,body])=><div className="panel p-7 transition-transform hover:-translate-y-1" key={num as string}><div className="mb-8 flex items-center justify-between"><div className="icon-box"><Icon size={19}/></div><span className="text-xs text-[#626a78]">{num as string}</span></div><h3 className="text-xl font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-7 muted">{body as string}</p></div>)}</div><button onClick={()=>navigate('/go-to-market-systems')} className="button-ghost mt-8">Explore our Go To Market System <ArrowRight size={16}/></button></div></section>
<section className="section-space bg-[#0d0f14]"><div className="container"><SectionHeading eyebrow="Case Studies" title="Feedback From Client Work"/><div className="mt-12 grid gap-4 md:grid-cols-6">{testimonials.map(([role,company,quote],i)=><a key={company} href={`/case-studies#${['sca-consultancy','tenable-business-support','sgs-security','the-cancer-conversation','re-roofs-repair'][i]}`} className={`panel group p-7 transition-all hover:-translate-y-1 hover:border-[rgba(30,144,255,.4)] ${i<3?'md:col-span-2':'md:col-span-2 md:mx-10'}`}><Quote className="mb-7 text-[#397fbe]" size={23}/><p className="min-h-24 text-lg leading-8 text-[#e7e9ed]">“{quote}”</p><div className="mt-8 border-t border-white/[.08] pt-5"><p className="text-sm font-semibold">{role}</p><p className="text-sm muted">{company}</p><p className="mt-5 inline-flex items-center gap-1 text-xs text-[#6bb7ff]">Read the case study <ArrowRight size={13} className="transition-transform group-hover:translate-x-1"/></p></div></a>)}</div></div></section>
<section className="section-space"><div className="container max-w-3xl"><SectionHeading align="center" eyebrow="FAQs" title="Frequently Asked Questions"/><div className="mt-12 divide-y divide-white/[.1] border-y border-white/[.1]">{faqs.map(([q,a],i)=><Faq key={q} q={q} a={a} open={i===0}/>)}</div></div></section>
<section className="container pb-24"><div className="relative overflow-hidden rounded-3xl border border-white/[.1] bg-[#121923] px-7 py-16 text-center"><div className="glow -right-40 -top-52 h-96 w-96"/><div className="relative"><p className="eyebrow mb-4">Ready to scale?</p><h2 className="display text-4xl font-bold sm:text-5xl">Build a better route to revenue.</h2><a href={bookingUrl} className="button-primary mt-8">Talk with our team <ArrowRight size={17}/></a></div></div></section>
</div>}
function Faq({q,a,open}:{q:string;a:string;open:boolean}){return <details open={open} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-base font-semibold">{q}<span className="icon-box h-7 w-7 shrink-0"><Plus size={16} className="group-open:hidden"/><ChevronDown size={16} className="hidden group-open:block"/></span></summary><p className="max-w-2xl pt-4 text-sm leading-7 muted">{a}</p></details>}
